from frappe import _

def get_data():
    return [
        {
            "module_name": "Daftra Sales",
            "color": "#3498db",
            "icon": "octicon octicon-inbox",
            "type": "module",
            "label": _("Sales"),
            "_category": "Sales",
        },
        {
            "module_name": "Daftra Clients",
            "color": "#2ecc71",
            "icon": "octicon octicon-organization",
            "type": "module",
            "label": _("Clients"),
            "_category": "Clients & CRM",
        },
        {
            "module_name": "Daftra Inventory",
            "color": "#e67e22",
            "icon": "octicon octicon-package",
            "type": "module",
            "label": _("Inventory"),
            "_category": "Inventory",
        },
        {
            "module_name": "Daftra Purchases",
            "color": "#9b59b6",
            "icon": "octicon octicon-repo-pull",
            "type": "module",
            "label": _("Purchases"),
            "_category": "Purchases",
        },
        {
            "module_name": "Daftra Accounting",
            "color": "#1abc9c",
            "icon": "octicon octicon-credit-card",
            "type": "module",
            "label": _("Accounting"),
            "_category": "Finance & Accounting",
        },
        {
            "module_name": "Daftra HR",
            "color": "#e74c3c",
            "icon": "octicon octicon-people",
            "type": "module",
            "label": _("HR & Employees"),
            "_category": "HR",
        },
        {
            "module_name": "Daftra POS",
            "color": "#f39c12",
            "icon": "octicon octicon-terminal",
            "type": "module",
            "label": _("POS"),
            "_category": "Sales",
        },
        {
            "module_name": "Daftra Bookings",
            "color": "#16a085",
            "icon": "octicon octicon-calendar",
            "type": "module",
            "label": _("Bookings"),
            "_category": "Operations",
        },
        {
            "module_name": "Daftra Time Tracking",
            "color": "#8e44ad",
            "icon": "octicon octicon-clock",
            "type": "module",
            "label": _("Time Tracking"),
            "_category": "Operations",
        },
        {
            "module_name": "Daftra Tax",
            "color": "#c0392b",
            "icon": "octicon octicon-law",
            "type": "module",
            "label": _("Tax & ZATCA"),
            "_category": "Settings",
        },
        {
            "module_name": "Daftra Projects",
            "color": "#34495e",
            "icon": "octicon octicon-briefcase",
            "type": "module",
            "label": _("Projects"),
            "_category": "Operations",
        },
        {
            "module_name": "Daftra Settings",
            "color": "#7f8c8d",
            "icon": "octicon octicon-settings",
            "type": "module",
            "label": _("Settings"),
            "_category": "Settings",
        },
    ]
