import frappe
from frappe import _
from frappe.model.document import Document
from frappe.utils import add_days, flt, getdate, nowdate

from daftra.api.project_api import sync_project_cost_center


class SalesInvoice(Document):
    def _apply_client_defaults(self):
        if not self.client:
            return
        client = frappe.get_doc('Client', self.client)
        if not self.payment_terms_days:
            self.payment_terms_days = client.credit_period or 30
        if client.client_type == 'Business' and not getattr(self, 'work_ordered_by', None):
            self.work_ordered_by = client.business_name or 'Business Client'

    def _apply_service_defaults(self):
        settings = frappe.get_single('Daftra Settings')
        is_service_mode = settings.business_type == 'Services'
        has_project_scope = bool(getattr(self, 'project_scope', None) or getattr(self, 'project_title', None))
        if is_service_mode or has_project_scope:
            if not self.invoice_layout or self.invoice_layout == 'Default Invoice':
                self.invoice_layout = 'Materials & Services'
            if not self.type_of_service:
                self.type_of_service = 'Maintenance'
            if not self.description_of_work:
                self.description_of_work = getattr(self, 'project_scope', None) or getattr(self, 'project_title', None) or 'Service project invoicing'
        if getattr(self, 'project_title', None) and not self.notes:
            self.notes = self.project_title
        sync_project_cost_center(self)

    def validate(self):
        if not self.invoice_date:
            self.invoice_date = nowdate()
        self._apply_client_defaults()
        self._apply_service_defaults()
        if self.payment_terms_days and not self.due_date:
            self.due_date = add_days(self.invoice_date, self.payment_terms_days)
        if self.due_date and getdate(self.due_date) < getdate(self.invoice_date):
            frappe.throw(_('Due Date cannot be before Invoice Date'))

        subtotal = 0
        tax_amount = 0
        settings = frappe.get_single('Daftra Settings')
        for row in self.get('items') or []:
            row.qty = flt(row.qty)
            row.rate = flt(row.rate)
            if row.qty <= 0:
                frappe.throw(_('Item quantity must be greater than zero'))
            if not row.description and row.item:
                row.description = frappe.db.get_value('Product', row.item, 'description') or row.item
            if not row.vat_rate and settings.enable_zatca:
                row.vat_rate = frappe.db.get_value('Product', row.item, 'vat_rate') if row.item else 0
            row.amount = row.qty * row.rate
            row.vat_amount = row.amount * flt(row.vat_rate) / 100
            subtotal += row.amount
            tax_amount += row.vat_amount

        self.subtotal = subtotal
        self.tax_amount = tax_amount
        self.total = subtotal - flt(self.discount_amount) - flt(self.deposit_amount) + flt(self.adjustment_amount) + tax_amount
        if self.total < 0:
            frappe.throw(_('Invoice total cannot be negative'))
        self.balance = self.total - flt(self.paid_amount)
        if self.balance <= 0 and self.total:
            self.status = 'Paid'
        elif self.docstatus == 1:
            self.status = 'Submitted'
        if settings.enable_zatca and self.invoice_layout == 'TAX Invoice' and not getattr(self, 'notes', None):
            self.notes = 'ZATCA tax invoice generated by Daftra.'
